"""
LaTeX & BibTeX export utility for SCI Research Platform.
Produces publication-ready .tex files compatible with major journal templates.
"""
from __future__ import annotations

import re
from typing import Dict, Any, List, Optional


# ─── LaTeX character escaping ──────────────────────────────────────────────

_LATEX_SPECIAL = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}

def _esc(text: str) -> str:
    """Escape special LaTeX characters in a string."""
    if not text:
        return ""
    result = []
    for char in text:
        result.append(_LATEX_SPECIAL.get(char, char))
    return "".join(result)


def _clean_section(text: str) -> str:
    """Remove markdown artifacts from AI-generated text for LaTeX."""
    if not text:
        return ""
    # Remove **bold** markdown
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)
    # Remove *italic* markdown
    text = re.sub(r"\*(.+?)\*", r"\\textit{\1}", text)
    # Remove ### headings → subsection
    text = re.sub(r"^#{3}\s*(.+)$", r"\\subsubsection{\1}", text, flags=re.MULTILINE)
    text = re.sub(r"^#{2}\s*(.+)$", r"\\subsection{\1}", text, flags=re.MULTILINE)
    text = re.sub(r"^#{1}\s*(.+)$", r"\\subsection{\1}", text, flags=re.MULTILINE)
    # Convert — to em-dash
    text = text.replace("—", "---").replace("–", "--")
    # Escape remaining special chars (but not already escaped)
    safe_chars = {"\\", "{", "}"}
    lines = []
    for line in text.split("\n"):
        if line.startswith("\\"):
            lines.append(line)
        else:
            safe = []
            i = 0
            while i < len(line):
                ch = line[i]
                if ch in _LATEX_SPECIAL and ch not in safe_chars:
                    safe.append(_LATEX_SPECIAL[ch])
                else:
                    safe.append(ch)
                i += 1
            lines.append("".join(safe))
    return "\n".join(lines)


# ─── BibTeX generation ────────────────────────────────────────────────────

def _author_last(name: str) -> str:
    """Return last name for BibTeX key."""
    parts = name.strip().split()
    return parts[-1].lower() if parts else "unknown"


def _make_bibtex_key(ref: Dict[str, Any], index: int) -> str:
    authors = ref.get("authors", [])
    first_author = authors[0] if authors else "Unknown"
    if isinstance(first_author, dict):
        first_author = first_author.get("name", "Unknown")
    last = _author_last(str(first_author))
    year = ref.get("year", "0000")
    word = re.sub(r"[^a-z]", "", (ref.get("title") or "")[:15].lower())
    return f"{last}{year}{word}" if word else f"{last}{year}ref{index}"


def _format_authors_bibtex(authors: List) -> str:
    result = []
    for a in authors[:8]:
        if isinstance(a, dict):
            a = a.get("name", "")
        parts = str(a).strip().split()
        if len(parts) >= 2:
            result.append(f"{parts[-1]}, {' '.join(parts[:-1])}")
        else:
            result.append(str(a))
    joined = " and ".join(result)
    if len(authors) > 8:
        joined += " and others"
    return joined


def generate_bibtex(references: List[Dict[str, Any]]) -> str:
    """Generate a complete .bib file from a list of reference dicts."""
    lines = ["% BibTeX references generated by SCI Research Platform", ""]
    for i, ref in enumerate(references):
        key = _make_bibtex_key(ref, i + 1)
        title = ref.get("title", "Untitled Reference")
        authors = _format_authors_bibtex(ref.get("authors", []))
        year = ref.get("year", "")
        journal = ref.get("journal") or ref.get("venue") or ""
        doi = ref.get("doi", "")
        url = ref.get("url", "")
        volume = ref.get("volume", "")
        pages = ref.get("pages", "")

        if doi or journal:
            entry_type = "article"
            lines.append(f"@article{{{key},")
            lines.append(f"  author  = {{{authors}}},")
            lines.append(f"  title   = {{{{{title}}}}},")
            if journal:
                lines.append(f"  journal = {{{journal}}},")
            if year:
                lines.append(f"  year    = {{{year}}},")
            if volume:
                lines.append(f"  volume  = {{{volume}}},")
            if pages:
                lines.append(f"  pages   = {{{pages}}},")
            if doi:
                lines.append(f"  doi     = {{{doi}}},")
            if url and not doi:
                lines.append(f"  url     = {{{url}}},")
            lines.append("}")
        else:
            lines.append(f"@misc{{{key},")
            lines.append(f"  author = {{{authors}}},")
            lines.append(f"  title  = {{{{{title}}}}},")
            if year:
                lines.append(f"  year   = {{{year}}},")
            if url:
                lines.append(f"  url    = {{{url}}},")
            lines.append("}")
        lines.append("")
    return "\n".join(lines)


# ─── Citation string formatters ───────────────────────────────────────────

def _cite_apa(ref: Dict, n: int) -> str:
    authors = ref.get("authors", [])
    names = [str(a.get("name", a) if isinstance(a, dict) else a) for a in authors[:6]]
    if len(authors) > 6:
        author_str = ", ".join(names[:6]) + " et al."
    elif len(names) > 1:
        author_str = ", ".join(names[:-1]) + ", & " + names[-1]
    else:
        author_str = names[0] if names else "Unknown"
    year = ref.get("year", "n.d.")
    title = ref.get("title", "Untitled")
    journal = ref.get("journal") or ""
    doi = ref.get("doi", "")
    doi_str = f" https://doi.org/{doi}" if doi else ""
    return f"{author_str}. ({year}). {title}. *{journal}*.{doi_str}"


def _cite_ieee(ref: Dict, n: int) -> str:
    authors = ref.get("authors", [])
    initials = []
    for a in authors[:3]:
        name = str(a.get("name", a) if isinstance(a, dict) else a).strip()
        parts = name.split()
        if len(parts) >= 2:
            initials.append(f"{'. '.join(p[0] for p in parts[:-1])}. {parts[-1]}")
        else:
            initials.append(name)
    if len(authors) > 3:
        initials.append("et al.")
    author_str = ", ".join(initials)
    year = ref.get("year", "")
    title = ref.get("title", "Untitled")
    journal = ref.get("journal") or ""
    doi = ref.get("doi", "")
    doi_str = f", doi: {doi}" if doi else ""
    return f"[{n}] {author_str}, \"{title},\" *{journal}*, {year}{doi_str}."


# ─── Main LaTeX generator ─────────────────────────────────────────────────

CITATION_STYLE_PACKAGES = {
    "apa":      r"\usepackage[natbibapa]{apacite}" + "\n" + r"\bibliographystyle{apacite}",
    "ieee":     r"\usepackage[numbers,sort&compress]{natbib}" + "\n" + r"\bibliographystyle{IEEEtran}",
    "mla":      r"\usepackage[natbibapa]{apacite}" + "\n" + r"\bibliographystyle{apacite}",
    "chicago":  r"\usepackage{natbib}" + "\n" + r"\bibliographystyle{chicago}",
    "harvard":  r"\usepackage[authoryear]{natbib}" + "\n" + r"\bibliographystyle{agsm}",
    "vancouver": r"\usepackage[numbers]{natbib}" + "\n" + r"\bibliographystyle{vancouver}",
    "nature":   r"\usepackage[numbers,sort&compress]{natbib}" + "\n" + r"\bibliographystyle{naturemag}",
    "acs":      r"\usepackage[numbers]{natbib}" + "\n" + r"\bibliographystyle{achemso}",
}


def generate_latex(project: Dict[str, Any]) -> str:
    """
    Generate a complete LaTeX document from a ResearchProject dict.
    Returns the .tex file content as a string.
    """
    title = _esc(project.get("title", "Research Paper"))
    domain = _esc(project.get("domain", ""))
    citation_style = (project.get("citation_style") or "ieee").lower()
    journal_type = (project.get("journal_type") or "IEEE").upper()

    # Authors
    authors_raw = project.get("all_authors") or []
    if not authors_raw:
        lead = project.get("author_name") or "Author"
        affil = project.get("author_affiliation") or "Institution"
        authors_raw = [{"name": lead, "affiliation": affil}]

    author_blocks = []
    for a in authors_raw:
        name = _esc(str(a.get("name", "Author")))
        affil = _esc(str(a.get("affiliation", "")))
        if affil:
            author_blocks.append(f"{name}\\\\\\small{{{affil}}}")
        else:
            author_blocks.append(name)
    author_str = " \\and ".join(author_blocks)

    # Keywords
    keywords = project.get("keywords") or []
    if isinstance(keywords, str):
        keywords = [k.strip() for k in keywords.split(",")]
    keywords_str = "; ".join(_esc(k) for k in keywords[:10])

    # Citation / bib packages
    bib_packages = CITATION_STYLE_PACKAGES.get(citation_style, CITATION_STYLE_PACKAGES["ieee"])
    bib_style_line = bib_packages.split("\n")[1]
    natbib_pkg = bib_packages.split("\n")[0]

    # Sections
    abstract = _clean_section(project.get("abstract") or "")
    introduction = _clean_section(project.get("introduction") or "")
    literature_review = _clean_section(project.get("literature_review") or "")
    methodology = _clean_section(project.get("methodology") or "")
    results = _clean_section(project.get("results") or "")
    discussion = _clean_section(project.get("discussion") or "")
    conclusion = _clean_section(project.get("conclusion") or "")

    # Author contributions / funding / COI
    author_contributions = _clean_section(project.get("author_contributions") or "")
    funding = _clean_section(project.get("funding_disclosure") or "")
    coi = _clean_section(project.get("conflicts_of_interest") or "")

    # References — generate inline bibliography
    references = project.get("references_data") or []
    bib_entries = []
    for i, ref in enumerate(references):
        bib_entries.append(_cite_ieee(ref, i + 1) if citation_style == "ieee" else _cite_apa(ref, i + 1))

    ref_section = ""
    if bib_entries:
        ref_lines = ["\\begin{thebibliography}{99}"]
        for i, entry in enumerate(bib_entries):
            # Convert basic markdown in citations
            entry = re.sub(r"\*(.+?)\*", r"\\textit{\1}", entry)
            ref_lines.append(f"  \\bibitem{{ref{i+1}}} {entry}")
        ref_lines.append("\\end{thebibliography}")
        ref_section = "\n".join(ref_lines)

    # Editor score metadata
    editor_score = project.get("editor_score")
    plagiarism_score = project.get("plagiarism_score")
    score_comment = ""
    if editor_score is not None:
        score_comment = f"% Editor Score: {editor_score:.1f}/10  |  Plagiarism: {plagiarism_score or 0:.1f}%  |  Journal: {journal_type}"

    latex = rf"""% ============================================================
% SCI Research Platform — LaTeX Export
% Generated for {journal_type} journal submission
{score_comment}
% ============================================================

\documentclass[12pt,a4paper]{{article}}

% ── Encoding & fonts ────────────────────────────────────────
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{times}}

% ── Page geometry ───────────────────────────────────────────
\usepackage[top=1in,bottom=1in,left=1.25in,right=1.25in]{{geometry}}
\usepackage{{setspace}}
\doublespacing

% ── Mathematics ─────────────────────────────────────────────
\usepackage{{amsmath,amssymb,amsthm}}

% ── Figures & tables ────────────────────────────────────────
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{array}}
\usepackage{{multirow}}
\usepackage{{tabularx}}
\usepackage{{float}}
\usepackage{{caption}}

% ── References ──────────────────────────────────────────────
{natbib_pkg}
\usepackage{{hyperref}}
\hypersetup{{
    colorlinks=true,
    linkcolor=blue,
    citecolor=blue,
    urlcolor=blue,
}}

% ── Abstract formatting ─────────────────────────────────────
\usepackage{{abstract}}
\renewcommand{{\abstractnamefont}}{{\normalfont\bfseries}}
\renewcommand{{\abstracttextfont}}{{\normalfont\small}}

% ── Section formatting ──────────────────────────────────────
\usepackage{{titlesec}}
\titleformat{{\section}}{{\large\bfseries}}{{\\thesection.}}{{0.5em}}{{}}
\titleformat{{\subsection}}{{\normalsize\bfseries}}{{\thesubsection.}}{{0.5em}}{{}}

% ── Line numbers (for review) ────────────────────────────────
\usepackage{{lineno}}

% ============================================================
\title{{{title}}}

\author{{{author_str}}}

\date{{}}

% ============================================================
\begin{{document}}

\maketitle
\linenumbers

% ── Abstract ────────────────────────────────────────────────
\begin{{abstract}}
{abstract}

\noindent\textbf{{Keywords:}} {keywords_str}
\end{{abstract}}

\newpage

% ── Introduction ────────────────────────────────────────────
\section{{Introduction}}
{introduction}

% ── Literature Review ───────────────────────────────────────
\section{{Literature Review}}
{literature_review}

% ── Materials and Methods ───────────────────────────────────
\section{{Materials and Methods}}
{methodology}

% ── Results ─────────────────────────────────────────────────
\section{{Results}}
{results}

% ── Discussion ──────────────────────────────────────────────
\section{{Discussion}}
{discussion}

% ── Conclusion ──────────────────────────────────────────────
\section{{Conclusion}}
{conclusion}

"""

    # Declarations
    declarations = []
    if author_contributions:
        declarations.append(rf"""\subsection*{{Author Contributions}}
{author_contributions}""")
    if funding:
        declarations.append(rf"""\subsection*{{Funding}}
{funding}""")
    if coi:
        declarations.append(rf"""\subsection*{{Declaration of Competing Interests}}
{coi}""")

    if declarations:
        latex += "\n% ── Declarations ────────────────────────────────────────\n"
        latex += "\n\n".join(declarations) + "\n\n"

    # References
    if ref_section:
        latex += "\n% ── References ─────────────────────────────────────────\n"
        latex += ref_section + "\n"
    else:
        latex += f"\n{bib_style_line}\n\\bibliography{{references}}\n"

    latex += "\n\\end{document}\n"
    return latex
